import hashlib
from datetime import date, timedelta

import numpy as np
import pandas as pd

from scripts.utils.config import BusinessRulesConfig
from scripts.utils.logger import get_logger
from scripts.utils.paths import get_raw_data_path
from scripts.utils.validation import raise_if_invalid, verify_dataset_integrity


logger = get_logger("CRMGenerator", "generation_execution.log")


class CRMGenerator:
    """Generates messy CRM account data for sales-to-billing reconciliation testing."""

    def __init__(self) -> None:
        self.config = BusinessRulesConfig()
        self.output_filename = "crm_accounts.csv"

        self.seed: int = int(self.config.project.get("random_seed", 42))
        self.orphan_account_count: int = 150
        self.duplicate_rate: float = 0.10
        self.bad_billing_link_rate: float = 0.02
        self.crm_missing_industry_rate: float = 0.05
        self.stale_activity_rate: float = 0.12
        self.organic_region_mismatch_rate: float = 0.02
        self.datapulse_region_mismatch_rate: float = 0.10

        self.billing_customers_path = (
            get_raw_data_path("billing") / "billing_customers.csv"
        )

    @staticmethod
    def _generate_crm_account_pk(crm_account_id: str) -> str:
        """Creates a deterministic stable surrogate key from CRM account ID."""
        return hashlib.md5(crm_account_id.strip().upper().encode("utf-8")).hexdigest()

    @staticmethod
    def _random_date_between(start_date: date, end_date: date) -> str:
        """Returns a random ISO-format date between two dates."""
        delta_days = (end_date - start_date).days

        if delta_days < 0:
            raise ValueError("start_date cannot be after end_date.")

        offset = np.random.randint(0, delta_days + 1)
        return (start_date + timedelta(days=int(offset))).isoformat()

    @staticmethod
    def _append_issue(issues: list[str], issue: str) -> None:
        """Adds a data quality issue to a record if not already present."""
        if issue not in issues:
            issues.append(issue)

    @staticmethod
    def _variant_account_name(customer_name: str) -> str:
        """Creates realistic CRM naming variations."""
        suffixes = [
            "Ltd",
            "Limited",
            "Inc",
            "Group",
            "Corporation",
            "PLC",
            "Holdings",
        ]

        return f"{customer_name} {np.random.choice(suffixes)}"

    @staticmethod
    def _derive_sales_territory(region_id: str) -> str:
        """Maps CRM region to a simple sales territory."""
        territory_map = {
            "US": "North America",
            "UK": "UK&I",
            "DE": "DACH",
            "SG": "APAC",
        }

        return territory_map.get(region_id, "Unassigned")

    def _load_billing_customers(self) -> pd.DataFrame:
        """Loads the billing customer source export generated by CustomerGenerator."""
        if not self.billing_customers_path.exists():
            raise FileNotFoundError(
                f"Billing customer file not found at {self.billing_customers_path}. "
                "Run CustomerGenerator before CRMGenerator."
            )

        df = pd.read_csv(
            self.billing_customers_path,
            dtype={
                "customer_id": "string",
                "legacy_id": "string",
                "region_id": "string",
                "currency_code": "string",
            },
        )

        required_columns = [
            "customer_pk",
            "customer_id",
            "legacy_id",
            "customer_name",
            "customer_segment",
            "industry",
            "region_id",
            "currency_code",
            "cohort_year",
            "is_acquired_customer",
            "acquisition_source",
            "created_date",
            "customer_status",
            "active_flag",
        ]

        is_valid, validation_logs = verify_dataset_integrity(
            df=df,
            required_columns=required_columns,
            unique_keys=["customer_id"],
        )

        for message in validation_logs:
            if is_valid:
                logger.info(message)
            else:
                logger.error(message)

        raise_if_invalid(is_valid, validation_logs)

        return df

    def _choose_mismatched_region(self, billing_region_id: str) -> str:
        """Chooses a CRM region that is guaranteed to differ from billing region."""
        valid_regions = [region["region_id"] for region in self.config.regions]
        possible_regions = [
            region_id for region_id in valid_regions if region_id != billing_region_id
        ]

        if not possible_regions:
            raise ValueError("Cannot create region mismatch with fewer than 2 regions.")

        return str(np.random.choice(possible_regions))

    def _should_create_region_mismatch(self, is_acquired_customer: bool) -> bool:
        """Applies hybrid mismatch probability logic."""
        mismatch_rate = (
            self.datapulse_region_mismatch_rate
            if is_acquired_customer
            else self.organic_region_mismatch_rate
        )

        return bool(np.random.random() < mismatch_rate)

    def _build_base_crm_account(self, row: pd.Series, index: int) -> dict:
        """Builds a base converted CRM account linked to a billing customer."""
        customer_id = str(row["customer_id"])
        crm_account_id = f"CRM-{customer_id}"

        is_acquired_customer = int(row["is_acquired_customer"]) == 1

        billing_region_id = str(row["region_id"])
        crm_region_id = billing_region_id

        issues: list[str] = []

        if self._should_create_region_mismatch(is_acquired_customer):
            crm_region_id = self._choose_mismatched_region(billing_region_id)
            self._append_issue(issues, "region_mismatch")

        industry = row["industry"]
        if pd.isna(industry) or np.random.random() < self.crm_missing_industry_rate:
            industry = None
            self._append_issue(issues, "missing_industry")

        created_date = str(row["created_date"])

        if np.random.random() < self.stale_activity_rate:
            last_activity_date = self._random_date_between(
                start_date=date(2022, 1, 1),
                end_date=date(2025, 12, 31),
            )
            self._append_issue(issues, "stale_activity")
        else:
            created_dt = date.fromisoformat(created_date)
            last_activity_date = self._random_date_between(
                start_date=created_dt,
                end_date=date(2026, 12, 31),
            )

        billing_customer_id = customer_id

        if np.random.random() < self.bad_billing_link_rate:
            billing_customer_id = f"INVALID-{index:06d}"
            self._append_issue(issues, "billing_link_mismatch")

        account_name = (
            self._variant_account_name(str(row["customer_name"]))
            if np.random.random() < 0.15
            else str(row["customer_name"])
        )

        return {
            "crm_account_pk": self._generate_crm_account_pk(crm_account_id),
            "crm_account_id": crm_account_id,
            "billing_customer_id": billing_customer_id,
            "account_name": account_name,
            "legal_entity_name": f"{row['customer_name']} Ltd",
            "customer_segment": row["customer_segment"],
            "industry": industry,
            "crm_region_id": crm_region_id,
            "billing_region_id": billing_region_id,
            "currency_code": row["currency_code"],
            "sales_owner_id": f"OWNER-{np.random.randint(1, 50):03d}",
            "sales_territory": self._derive_sales_territory(crm_region_id),
            "account_status": "Closed-Won",
            "lead_source": np.random.choice(
                ["Outbound", "Inbound", "Partner", "Event", "Referral"],
                p=[0.35, 0.30, 0.15, 0.10, 0.10],
            ),
            "created_date": created_date,
            "last_activity_date": last_activity_date,
            "is_converted_customer": 1,
            "is_duplicate_record": 0,
            "duplicate_group_id": None,
            "data_quality_flag": int(len(issues) > 0),
            "data_quality_issue": "|".join(issues) if issues else None,
            "active_flag": 1,
        }

    def _build_duplicate_crm_account(self, row: pd.Series, duplicate_index: int) -> dict:
        """Builds a duplicate CRM record pointing to the same billing customer."""
        customer_id = str(row["customer_id"])
        crm_account_id = f"CRM-DUP-{duplicate_index:06d}"

        issues = ["duplicate"]

        industry = row["industry"]
        if pd.isna(industry) or np.random.random() < self.crm_missing_industry_rate:
            industry = None
            self._append_issue(issues, "missing_industry")

        last_activity_date = (
            self._random_date_between(date(2022, 1, 1), date(2025, 12, 31))
            if np.random.random() < self.stale_activity_rate
            else self._random_date_between(date(2026, 1, 1), date(2026, 12, 31))
        )

        if last_activity_date < "2026-07-01":
            self._append_issue(issues, "stale_activity")

        billing_region_id = str(row["region_id"])
        crm_region_id = billing_region_id

        return {
            "crm_account_pk": self._generate_crm_account_pk(crm_account_id),
            "crm_account_id": crm_account_id,
            "billing_customer_id": customer_id,
            "account_name": self._variant_account_name(str(row["customer_name"])),
            "legal_entity_name": f"{row['customer_name']} Ltd",
            "customer_segment": row["customer_segment"],
            "industry": industry,
            "crm_region_id": crm_region_id,
            "billing_region_id": billing_region_id,
            "currency_code": row["currency_code"],
            "sales_owner_id": f"OWNER-{np.random.randint(1, 50):03d}",
            "sales_territory": self._derive_sales_territory(crm_region_id),
            "account_status": "Closed-Won",
            "lead_source": "Migration",
            "created_date": row["created_date"],
            "last_activity_date": last_activity_date,
            "is_converted_customer": 1,
            "is_duplicate_record": 1,
            "duplicate_group_id": f"GRP-{customer_id}",
            "data_quality_flag": 1,
            "data_quality_issue": "|".join(issues),
            "active_flag": 1,
        }

    def _build_orphan_crm_account(self, index: int) -> dict:
        """Builds a CRM prospect account that has no billing customer."""
        crm_account_id = f"CRM-ORPH-{index:06d}"

        region = np.random.choice(self.config.regions)
        region_id = str(region["region_id"])
        currency_code = str(region["currency_code"])

        created_date = self._random_date_between(
            start_date=date(2024, 1, 1),
            end_date=date(2026, 12, 31),
        )

        last_activity_date = self._random_date_between(
            start_date=date(2024, 1, 1),
            end_date=date(2026, 12, 31),
        )

        issues = ["orphan"]

        if np.random.random() < self.crm_missing_industry_rate:
            industry = None
            self._append_issue(issues, "missing_industry")
        else:
            industry_options = [item["industry"] for item in self.config.customer_industries]
            industry_weights = [float(item["share"]) for item in self.config.customer_industries]
            industry = np.random.choice(industry_options, p=industry_weights)

        if np.random.random() < self.stale_activity_rate:
            last_activity_date = self._random_date_between(
                start_date=date(2022, 1, 1),
                end_date=date(2025, 12, 31),
            )
            self._append_issue(issues, "stale_activity")

        return {
            "crm_account_pk": self._generate_crm_account_pk(crm_account_id),
            "crm_account_id": crm_account_id,
            "billing_customer_id": None,
            "account_name": f"Prospect Corp {index:04d}",
            "legal_entity_name": f"Prospect Corp {index:04d} Inc",
            "customer_segment": np.random.choice(
                ["SMB", "Mid-Market", "Enterprise"],
                p=[0.70, 0.25, 0.05],
            ),
            "industry": industry,
            "crm_region_id": region_id,
            "billing_region_id": None,
            "currency_code": currency_code,
            "sales_owner_id": f"OWNER-{np.random.randint(1, 50):03d}",
            "sales_territory": self._derive_sales_territory(region_id),
            "account_status": "Prospect",
            "lead_source": np.random.choice(
                ["Web", "Outbound", "Event", "Partner"],
                p=[0.40, 0.30, 0.20, 0.10],
            ),
            "created_date": created_date,
            "last_activity_date": last_activity_date,
            "is_converted_customer": 0,
            "is_duplicate_record": 0,
            "duplicate_group_id": None,
            "data_quality_flag": 1,
            "data_quality_issue": "|".join(issues),
            "active_flag": 1,
        }

    def generate(self) -> pd.DataFrame:
        """Generates the messy CRM account source export."""
        logger.info("Generating CRM accounts with controlled defects.")

        np.random.seed(self.seed)

        billing_df = self._load_billing_customers()

        records: list[dict] = []

        for index, row in billing_df.iterrows():
            records.append(self._build_base_crm_account(row=row, index=index + 1))

        duplicate_count = int(len(billing_df) * self.duplicate_rate)
        duplicate_indices = np.random.choice(
            billing_df.index,
            size=duplicate_count,
            replace=False,
        )

        for duplicate_number, source_index in enumerate(duplicate_indices, start=1):
            records.append(
                self._build_duplicate_crm_account(
                    row=billing_df.loc[source_index],
                    duplicate_index=duplicate_number,
                )
            )

        for orphan_index in range(1, self.orphan_account_count + 1):
            records.append(self._build_orphan_crm_account(index=orphan_index))

        df = pd.DataFrame(records)

        required_columns = [
            "crm_account_pk",
            "crm_account_id",
            "billing_customer_id",
            "account_name",
            "legal_entity_name",
            "customer_segment",
            "industry",
            "crm_region_id",
            "billing_region_id",
            "currency_code",
            "sales_owner_id",
            "sales_territory",
            "account_status",
            "lead_source",
            "created_date",
            "last_activity_date",
            "is_converted_customer",
            "is_duplicate_record",
            "duplicate_group_id",
            "data_quality_flag",
            "data_quality_issue",
            "active_flag",
        ]

        df = df[required_columns]

        is_valid, validation_logs = verify_dataset_integrity(
            df=df,
            required_columns=required_columns,
            unique_keys=["crm_account_pk"],
        )

        for message in validation_logs:
            if is_valid:
                logger.info(message)
            else:
                logger.error(message)

        raise_if_invalid(is_valid, validation_logs)

        expected_rows = (
            len(billing_df)
            + int(len(billing_df) * self.duplicate_rate)
            + self.orphan_account_count
        )

        if len(df) != expected_rows:
            raise ValueError(
                f"CRM row count mismatch. Expected {expected_rows}, got {len(df)}."
            )

        if df["crm_account_id"].nunique() != len(df):
            raise ValueError("CRM account export contains duplicate crm_account_id values.")

        orphan_count = int(df["billing_customer_id"].isna().sum())
        if orphan_count != self.orphan_account_count:
            raise ValueError(
                f"CRM orphan count mismatch. Expected {self.orphan_account_count}, got {orphan_count}."
            )

        duplicate_count_actual = int(df["is_duplicate_record"].sum())
        if duplicate_count_actual != duplicate_count:
            raise ValueError(
                f"CRM duplicate count mismatch. Expected {duplicate_count}, got {duplicate_count_actual}."
            )

        logger.info("Generated CRM account export with %s rows.", len(df))

        return df

    def save(self, df: pd.DataFrame) -> None:
        output_dir = get_raw_data_path("crm")
        output_path = output_dir / self.output_filename

        df.to_csv(output_path, index=False, encoding="utf-8")

        logger.info("CRM account export written to %s", output_path)


def main() -> None:
    generator = CRMGenerator()
    df = generator.generate()
    generator.save(df)


if __name__ == "__main__":
    main()